### ISSUE TITLE
slot failure immediately after removal from resolver leads to sadness

### ISSUE THREAD

**Issue by arekinath** [TritonDataCenter/node-cueball#144]
At https://github.com/joyent/node-cueball/blob/v2.7.0/lib/pool.js#L708 we don't have a check for whether the backend is still in the resolver or not, so we can end up creating an entry in `p_dead` for a backend that's actually gone. This then results in the number of keys in `p_dead` being stuck higher than it should be, leading to us going into the `failed` state even though nothing we actually care about is dead.

**Comment by trentm** [comment]
A symptom of this was a number of moray processes in Triton moray zones occasionally going into a state where requests would respond with `Error('connect ECONNREFUSED')`. E.g.:

```
[root@5533e7bb-9cf0-4b63-bb03-013aa622c570 (nightly-1:moray1) /opt/smartdc/moray/node_modules/fast]# while true; do sleep 1; echo "--"; for port in 2021 2022 2023 2024; do echo -n "$port: " ; getbucket -p $port imgapi_images | head -1; done; done
--
...
2021: {
2022: getbucket: moray client ("127.0.0.1:49384" to "127.0.0.1:2022"): request failed: server error: connect ECONNREFUSED
2023: {
2024: {
```

**Comment by trentm** [comment]
https://jira.joyent.us/browse/TRITON-620 opened for the moray nightly-1 failures for this.

**Comment by arekinath** [comment]
https://cr.joyent.us/#/c/4564 is the CR

The auto-test it adds fails before the patch to `pool.js` is applied (and reflects the symptoms we've seen in cores of TRITON-620). It's notable that in `set.js` we already guard the dead marking in this way (I guess we observed this race with moray *clients* before already)
